truthtable:	truthtable.cpp
			g++ truthtable.cpp -o truthtable

run:	truthtable
			./truthtable A+B
			./truthtable D+E+F
			./truthtable M.N.O
			./truthtable K.L
			./truthtable P.Q.R.S

clean:
		rm -f truthtable
